environments:
  production:
  ci:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts

releases:
- name: matrix-server
  chart: w3f/matrix-server
  version: v0.5.0
  values:
  - image:
      repo: web3f/synapse
      tag: v0.99.5.2-antiscam
  - environment: {{ .Environment.Name }}
  - db:
      user: {{ env "DB_USER" | default "synapse_user" }}
      password: '{{ env "DB_PASSWORD" | default "pass" }}'
      name: {{ env "DB_NAME" | default "synapse" }}
    recaptcha:
      publicKey: {{ env "RECAPTCHA_PUBLIC_KEY" | default "recaptcha_public" }}
      privateKey: {{ env "RECAPTCHA_PRIVATE_KEY" | default "recaptcha_private" }}
    macaroonSecretKey: {{ env "MACAROON_SECRET_KEY" | default "macaroon_secret" }}
    formSecret: {{ env "FORM_SECRET" | default "form_secret" }}
    signingKey: {{ env "SIGNING_KEY" | default "signing_key" | quote }}
    domain: polkadot.builders
    emailPattern: '.*'
    autojoinRooms:
    - "#arrivals:polkadot.builders"
    antiscam: true

- name: riot-web
  chart: w3f/riot-web
  version: v0.4.2
  values:
  - environment: {{ .Environment.Name }}
    domain: polkadot.builders
    matrixDomain: polkadot.builders
    brand: "Polkadot Builders"
